version: "3.3"
services:

  workspace:
    build:
      dockerfile: Dockerfile
    environment:
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar
      OTEL_EXPORTER_OTLP_ENDPOINT: http://62.76.228.98:4327
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://62.76.228.98:4327
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME}
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_PASSWORD: ${GITHUB_PASSWORD}
    ports:
      - "48006:48006"